### ISSUE TITLE
cb:fan 沒見到有文檔。似乎和cb:yin用途類似？

### ISSUE THREAD

**Issue by CallMeNP** [DILA-edu/cbeta-documentation#1]
cb:fan 一般形式是：
```xml
<cb:fan>
    <cb:zi>若</cb:zi>
    <cb:yin>荏蔗切</cb:yin>
</cb:fan>
```
cb:yin 一般形式是：
```xml
<cb:yin>
    <cb:zi></cb:zi>
    <cb:sg></cb:sg>
</cb:yin>
```
cb:sg 在文檔有註明，有屬性值 fangie 代表“反切”。那麼與cb:fan 應該就是重複的功能了吧。

**Comment by RayCHOU** [comment]
感謝提問。

新增了 fan 元素的文檔： https://github.com/DILA-edu/cbeta-documentation/blob/master/xml/p5a/elements/fan.md

另外也更新了 yin 的文檔： https://github.com/DILA-edu/cbeta-documentation/blob/master/xml/p5a/elements/yin.md

yin 用法的其中一種，的確是與 fan 有功能上的重複。
